// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGdJEeotYvnqMsOdu8iAXN3yYtjElVNI',
    appId: '1:813677543194:web:6466176a078d053fd736a3',
    messagingSenderId: '813677543194',
    projectId: 'fir-study1-4e6b1',
    authDomain: 'fir-study1-4e6b1.firebaseapp.com',
    storageBucket: 'fir-study1-4e6b1.firebasestorage.app',
    measurementId: 'G-VLPJK10RF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdjeUrvTXWOt3Fv5GuszHtwFdkqctZ44',
    appId: '1:813677543194:android:9c21ee02482b9d7fd736a3',
    messagingSenderId: '813677543194',
    projectId: 'fir-study1-4e6b1',
    storageBucket: 'fir-study1-4e6b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsY9qnHEPM9cmog3Bz5BeiGMowx_k3Gb0',
    appId: '1:813677543194:ios:b2f5a3f780a90420d736a3',
    messagingSenderId: '813677543194',
    projectId: 'fir-study1-4e6b1',
    storageBucket: 'fir-study1-4e6b1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsY9qnHEPM9cmog3Bz5BeiGMowx_k3Gb0',
    appId: '1:813677543194:ios:b2f5a3f780a90420d736a3',
    messagingSenderId: '813677543194',
    projectId: 'fir-study1-4e6b1',
    storageBucket: 'fir-study1-4e6b1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKGdJEeotYvnqMsOdu8iAXN3yYtjElVNI',
    appId: '1:813677543194:web:c71fd140feceb8bed736a3',
    messagingSenderId: '813677543194',
    projectId: 'fir-study1-4e6b1',
    authDomain: 'fir-study1-4e6b1.firebaseapp.com',
    storageBucket: 'fir-study1-4e6b1.firebasestorage.app',
    measurementId: 'G-F8TMEXPQV6',
  );

}